name: On-chain Dependency Installation
description: Installs Python dependencies if requirements.txt is present.
runs:
  using: "composite"
  steps:
    - name: Install dependencies for build and tests
      shell: bash
      run: |
        if [ -f requirements.txt ]; then
          sudo apt-get update
          sudo apt-get install -y python3-pip curl
          pip3 install -r requirements.txt
        fi
