name: Checks formatting using language-appropriate tooling
description: If formatting changes are needed, this action will fail and provide a diff of the required changes. This can be used as a PR check.
inputs:
  formatter:
    description: The formatter to use. If not provided, the action will attempt to auto-detect based on the presence of configuration files.
    required: false
    default: auto
  path:
    description: Comma-separated list of files or directories to format (e.g. "src,tests,docs"). If not provided, defaults to the entire repository.
    required: false
    default: .
  config-file:
    description: Path to the configuration file for the selected formatter (e.g., Prettier, Black). If not provided, the formatter's default settings will be used.
    required: false
runs:
  using: 'composite'
  steps:
    # A note on directories: Due to nodejs module conflicts, prettier and its plugins cannot share a directory with a nodejs project.
    # Thus, install prettier in a temp directory and checkout the project files separately.
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        path: project-files
    
    - name: Determine formatter tool
      id: determine-formatter
      shell: bash
      working-directory: project-files
      run: |
        echo "::group::Determining formatter"
        # Autodetect
        if [ "${{ inputs.formatter }}" != "auto" ]; then
          formatter="${{ inputs.formatter }}"
        # Foundry
        elif [ -f "foundry.toml" ]; then
          formatter="forge"
        # Python (Black)
        elif [ -f "requirements.txt" ] || [ -f "pyproject.toml" ]; then
          formatter="black"
          options=${{ inputs.config-file != '' && format('--config {0}', inputs.config-file) || '' }}
        # Go (gofmt)
        elif [ -f "go.mod" ]; then
          formatter="gofmt"
        # Prettier (keep this last, as non-nodejs projects may have a package.json)
        elif [ -f ".prettierrc" ] || [ -f ".prettierrc.json" ] || [ -f "prettier.config.js" ] || [ -f "package.json" ]; then
          mkdir -p ${{ runner.temp }}/prettier-tool
          formatter="prettier"
          options=${{ inputs.config-file != '' && format('--config {0}', inputs.config-file) || '' }}
        else
          formatter="none"
          echo "::error::No formatter could be determined. Please specify a formatter using the 'formatter' input."
          exit 1
        fi
        echo "::endgroup::"
        echo "formatter=$formatter" >> $GITHUB_OUTPUT
        echo "options=$options" >> $GITHUB_OUTPUT
        echo "Using formatter: $formatter"

    - name: Install Black
      if: ${{ steps.determine-formatter.outputs.formatter == 'black' }}
      shell: bash
      run: |      
        echo "Installing Black"
        python3 -m pip install --upgrade pip
        pip install black

    # TODO: Add support for foundry/forge later if not a separate action

    - name: Install Golang
      if: ${{ steps.determine-formatter.outputs.formatter == 'gofmt' }}
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    # Prettier can't share a directory with nodejs project, so use a temp directory
    - name: Install Prettier
      if: ${{ steps.determine-formatter.outputs.formatter == 'prettier' }}
      shell: bash
      working-directory: ${{ runner.temp }}/prettier-tool
      run: |
        echo "::group::Installing Prettier at ${{ runner.temp }}/prettier-tool"
        npm install prettier
        npm install prettier-plugin-sh
        npm why prettier
        echo "::endgroup::"

    - name: Symlink Prettier plugins into project
      if: ${{ steps.determine-formatter.outputs.formatter == 'prettier' }}
      shell: bash
      working-directory: project-files
      run: |
        ## Symlink the plugins into the project directory (Prettier loads them relative to the project config file)
        mkdir -p node_modules
        ln -s ${{ runner.temp }}/prettier-tool/node_modules/prettier-plugin-sh ./node_modules/prettier-plugin-sh

    - name: Get changed files
      id: changed-files
      shell: bash
      working-directory: project-files
      run: |
        echo "::group::Determining changed files"
        # PR context OR branch vs. default branch
        if [ "${{ github.event_name }}" == "pull_request" ]; then
          # Get files changed in PR
          git fetch origin ${{ github.base_ref }}
          CHANGED_FILES=$(git diff --name-only origin/${{ github.base_ref }}...HEAD)
        else
          git fetch origin ${{ github.event.repository.default_branch }}
          CHANGED_FILES=$(git diff --name-only origin/${{ github.event.repository.default_branch }}...HEAD)
        fi
        echo "changed_files<<EOF" >> $GITHUB_OUTPUT
        echo "$CHANGED_FILES" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
        echo "::endgroup::"

    - name: Run formatter check
      id: format-check
      continue-on-error: true
      shell: bash
      # projects need to be in a separate directory, as prettier plugins use node_modules which conflict with nodejs projects
      working-directory: project-files
      run: |
        ${{ github.action_path }}/../../scripts/check-format.sh \
          "${{ steps.determine-formatter.outputs.formatter }}" \
          "${{ steps.determine-formatter.outputs.options }}" \
          "${{ steps.changed-files.outputs.changed_files }}" >> $GITHUB_OUTPUT

    - name: Debug - Print format-check outputs
      if: always()
      shell: bash
      run: |
        echo "Format check outputs:"
        echo "Unformatted files: ${{ steps.format-check.outputs.unformatted_files }}"

    - name: Find existing comment
      if: steps.format-check.outcome == 'failure' && github.event_name == 'pull_request'
      id: find-comment
      uses: peter-evans/find-comment@v3
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: 'github-actions[bot]'
        body-includes: '<!-- format-check-comment -->'

    - name: Create or update PR comment
      if: steps.format-check.outcome == 'failure' && github.event_name == 'pull_request'
      uses: peter-evans/create-or-update-comment@v4
      with:
        token: ${{ github.token }}
        comment-id: ${{ steps.find-comment.outputs.comment-id }}
        issue-number: ${{ github.event.pull_request.number }}
        edit-mode: replace
        body: |
          <!-- format-check-comment -->
          ## ⚠️ Formatting Issues Detected
          
          The following files need formatting with `${{ steps.determine-formatter.outputs.formatter }}`:
          
          ```
          ${{ steps.format-check.outputs.unformatted_files }}
          ```

          Please run the formatter locally to fix these issues.

    - name: Exit with error if formatting needed
      if: steps.format-check.outcome == 'failure'
      shell: bash
      run: |
        echo "Formatting check failed. Files need formatting."
        exit 1
