name: Python Setup
description: Set up Python toolchain in the repository
runs:
  using: "composite"
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.13"
