name: On-chain Test
description: Runs forge build and test commands for on-chain microservices.
inputs:
  alchemy_eth_api:
    description: The Alchemy API key to use for Ethereum RPC calls.
    required: false
  alchemy_polygon_api:
    description: The Alchemy API key to use for Polygon RPC calls.
    required: false
runs:
  using: 'composite'
  steps:
    - name: Run Foundry tests
      shell: bash
      env:
        ETHEREUM_RPC_KEY: ${{ inputs.alchemy_eth_api }}
        POLYGON_RPC_KEY: ${{ inputs.alchemy_polygon_api }}
      run: |
        forge test --ffi
      id: forge-test
