name: On-chain Test
description: Runs forge build and test commands for on-chain microservices.
inputs:
  alchemy_eth_api:
    description: The Alchemy API URI to use for Ethereum RPC calls.
    required: false
  alchemy_polygon_api:
    description: The Alchemy API URI to use for Polygon RPC calls.
    required: false
  fork-test:
    description: Whether to run tests that require forking mainnet.
    required: false
    default: "false"
  salt-string:
    description: Salt string for generating unique addresses in tests.
    required: false
    default: "SMELLING_SALTS"
  skip-forte-token-tests:
    description: Whether to skip tests related to Forte Token.
    required: false
    default: "true"
  is-forte-token-project:
    description: Whether this is the Forte Token project.
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - name: Run Foundry tests
      shell: bash
      env:
        ETHEREUM_RPC_KEY: ${{ inputs.alchemy_eth_api }}
        POLYGON_RPC_KEY: ${{ inputs.alchemy_polygon_api }}
        FORK_TEST: ${{ inputs['is-forte-token-project'] == 'true' && inputs['fork-test'] || 'false' }}
        SALT_STRING: ${{ inputs['is-forte-token-project'] == 'true' && inputs['salt-string'] || 'SMELLING_SALTS' }}
        SKIP_FORTE_TOKEN_TESTS: ${{ inputs['is-forte-token-project'] == 'true' && inputs['skip-forte-token-tests'] || 'true' }}
      run: |
        forge test --ffi
      id: forge-test
