name: Python Dependency Installer
description: Install Python dependencies from requirements files
inputs:
  requirements-file:
    description: "Path to the requirements file"
    required: false
    default: "requirements.txt"
runs:
  using: "composite"
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        if [ -f "${{ inputs.requirements-file }}" ]; then
          pip install -r "${{ inputs.requirements-file }}"
        else
          echo "::warning:: Requirements file not found: ${{ inputs.requirements-file }}"
        fi
