name: Golang Setup
description: Set up Go toolchain in the repository
inputs:
  go-version:
    description: "Go version to install"
    required: false
    default: "1.25"
runs:
  using: "composite"
  steps:
    - name: Install Golang
      uses: actions/setup-go@v4
      with:
        go-version: ${{ inputs.go-version }}

    - name: Download Go dependencies
      shell: bash
      run: |
        go mod download

    - name: Verify Go dependencies
      shell: bash
      run: |
        go mod verify
