name: On-chain Build + Test
description: Runs forge build and contract size checks for on-chain microservices.
runs:
  using: "composite"
  steps:
    - name: Check Contract Size
      shell: bash
      run: |
        bash infrastructure-tooling/.github/scripts/contract-size.sh
