name: Golang Code Coverage
description: Runs code coverage evaluation for a go project.
runs:
  using: "composite"
  steps:

    - name: Check test coverage
      run: |
        coverage=$(go tool cover -func=coverage.out | grep total | awk '{print $3}' | sed 's/%//')
        echo "Test coverage: ${coverage}%"
        if (( $(echo "$coverage < 40" | bc -l) )); then
          echo "Test coverage is below 40%"
          exit 1
        fi
    
    - name: Generate coverage report
      run: go tool cover -html=coverage.out -o coverage.html
    
    - name: Get coverage percentage
      id: coverage
      run: |
        coverage=$(go tool cover -func=coverage.out | grep total | awk '{print $3}' | sed 's/%//')
        echo "percentage=$coverage" >> $GITHUB_OUTPUT
    
    - name: Comment PR with coverage
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const coveragePercent = '${{ steps.coverage.outputs.percentage }}';
          
          const body = `## Test Results
          
          ✅ All tests passed!
          
          **Test Coverage:** ${coveragePercent}%
          
          Run \`make test-coverage\` locally to view detailed coverage report.`;
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: body
          })
