name: Rust Test
description: Run Rust tests in the repository
inputs:
  working-directory:
    description: The working directory to run the tests in. Defaults to the repository root.
    required: false
    default: .
runs:
  using: 'composite'
  steps:
    - name: Set up Rust
      uses: dtolnay/rust-toolchain@nightly
      with:
        components: rustfmt, clippy
