name: Package Version Check
description: Validates package.json versions are consistent and incremented

runs:
  using: composite
  steps:
    - name: Check versions
      id: check
      shell: bash
      run: |
        set +e # Allow the script to exit non-zero and continue the workflow
        result=$("${{ github.action_path }}/../../scripts/check-versions.sh" "${{ github.event.repository.default_branch }}")
        exit_code=$?
        
        if [ $exit_code -eq 0 ]; then
          echo "status=pass" >> $GITHUB_OUTPUT
        else
          echo "status=fail" >> $GITHUB_OUTPUT
          echo "comment<<EOF" >> $GITHUB_OUTPUT
          echo "$result" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        fi

    - name: Find existing comment
      if: steps.check.outputs.status == 'failure' && github.event_name == 'pull_request'
      id: find-comment
      uses: peter-evans/find-comment@v3
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: 'github-actions[bot]'
        body-includes: '<!-- version-check-comment -->'

    - name: Create or update PR comment
      if: steps.check.outputs.status == 'failure' && github.event_name == 'pull_request'
      uses: peter-evans/create-or-update-comment@v4
      with:
        token: ${{ github.token }}
        comment-id: ${{ steps.find-comment.outputs.comment-id }}
        issue-number: ${{ github.event.pull_request.number }}
        edit-mode: replace
        body: ${{ steps.check.outputs.comment }}

    - name: Exit with error if formatting needed
      if: steps.check.outputs.status == 'failure'
      shell: bash
      run: |
        echo "Version check failed. Please update `package.json` versions."
        exit 1





    # - name: Comment on PR
    #   if: steps.check.outputs.status == 'fail'
    #   uses: thollander/actions-comment-pull-request@v3
    #   with:
    #     message: ${{ steps.check.outputs.comment }}
    #     comment_tag: version-check

    # - name: Delete comment on success
    #   if: steps.check.outputs.status == 'pass'
    #   uses: thollander/actions-comment-pull-request@v3
    #   with:
    #     message: ''
    #     comment_tag: version-check
    #     mode: delete

    # - name: Fail if checks failed
    #   if: steps.check.outputs.status == 'fail'
    #   shell: bash
    #   run: exit 1
