name: On-chain Dependency Installation
description: Install dependencies
runs:
  using: "composite"
  steps:
    - name: Installs Python dependencies if requirements.txt is present.
      shell: bash
      run: |
        if [ -f requirements.txt ]; then
          sudo apt-get update
          sudo apt-get install -y python3-pip curl
          pip3 install -r requirements.txt
          # Debugging
          which forge
        fi
