name: On-chain Slither Analysis
description: Runs forge build and slither analysis for on-chain microservices.
inputs:
  CONFIG:
    description: Path to slither config file
    required: false
    default: ./slither.config.json
runs:
  using: "composite"
  steps:
    - name: Slither Analyze
      id: slither
      shell: bash
      run: |
        forge install dapphub/ds-test
        forge install OpenZeppelin/openzeppelin-contracts
        pip install slither-analyzer
        slither --config-file ${{ inputs.CONFIG }} --sarif results.sarif --fail-none .

    - name: Upload SARIF file
      uses: actions/upload-artifact@v4
      with:
        name: results.sarif
        path: ./results.sarif
        retention-days: 5

    - name: Create/update checklist as PR comment
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const path = require('path');
          // Read the SARIF file
          const sarifPath = './results.sarif';
          let sarifContent = '';
          try {
            if (fs.existsSync(sarifPath)) {
              const rawContent = fs.readFileSync(sarifPath, 'utf8');
              const sarifData = JSON.parse(rawContent);
              // Format the SARIF data for better readability
              let formattedResults = '';
              if (sarifData.runs && sarifData.runs.length > 0) {
                for (const run of sarifData.runs) {
                  if (run.results && run.results.length > 0) {
                    formattedResults += `## ${run.tool.driver.name} Analysis Results\n\n`;
                    formattedResults += `Found ${run.results.length} issue(s):\n\n`;
                    for (const result of run.results) {
                      const level = result.level || 'info';
                      const ruleId = result.ruleId || 'unknown';
                      const message = result.message.text || 'No message';
                      const location = result.locations && result.locations[0] 
                        ? `${result.locations[0].physicalLocation.artifactLocation.uri}:${result.locations[0].physicalLocation.region.startLine}`
                        : 'Unknown location';

                      formattedResults += `- **${level.toUpperCase()}** [${ruleId}]: ${message}\n`;
                      formattedResults += `  - Location: \`${location}\`\n\n`;
                    }
                  } else {
                    formattedResults += `## ${run.tool.driver.name} Analysis Results\n\n`;
                    formattedResults += '✅ No issues found!\n\n';
                  }
                }
              } else {
                formattedResults = '✅ No analysis results found.\n';
              }
              sarifContent = formattedResults;
            } else {
              sarifContent = '❌ SARIF file not found.';
            }
          } catch (error) {
            sarifContent = `❌ Error reading SARIF file: ${error.message}`;
          }
          const header = '<details><summary>🔍 Slither Analysis Report</summary>\n\n';
          const footer = '\n</details>';
          const comment = header + sarifContent + footer;
          const { data: comments } = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.payload.number,
          });
          const botComment = comments.find(
            (comment) =>
              // github-actions bot user
              comment.user.id === 41898282 && comment.body.includes('🔍 Slither Analysis Report')
          );
          const commentFn = botComment ? "updateComment" : "createComment";
          await github.rest.issues[commentFn]({
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment,
            ...(botComment
              ? { comment_id: botComment.id }
              : { issue_number: context.payload.number }),
          });
